extends Resource

const NAMES := [
	'pepe mujica',
	'ernesto pérez',
	'rosa melano',
	'casimiro cuco',
	'elbert galarga',
	'elbert galarga ii',
	'elbert galarga iii',
	'elbert galarga iv',
]
const ARCANES := [
	'the magician',
	'the high priestess',
	'the empress',
	'the emperor',
	'the hierophant',
	'the lovers',
	'the chariot',
	'strength',
	'the hermit',
	'wheel of fortune',
	'justice',
	'the hanged man',
	'death',
	'temperance',
	'the devil',
	'the tower',
	'the star',
	'the moon',
	'the sun',
	'judgement',
	'the world',
	'the fool',
]
const DEATHS := [
	'suicide',
	'murder',
	'extrangulation',
	'accident',
	'passion',
	'slip',
	'carelessness',
	'jealousy',
]
